spring.application.name=auth
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
server.port=8080

spring.devtools.livereload.enabled=true
#logging.level.org.springframework=DEBUG

auth-ms.app.jwtSecret=${auth-ms.app.jwtSecret}
auth-ms.app.jwtExpirationMs=${auth-ms.app.jwtExpirationMs}
auth-ms.app.jwtRefreshExpirationMs=${auth-ms.app.jwtRefreshExpirationMs}

# En el entorno de desarrollo
spring.profiles.active=dev
# En el entorno de producción
#spring.profiles.active=prod

logging.level.org.springframework.security=DEBUG
